"""Bakery plugin for deploying the Java Keystore certificate monitor agent plugin.

Uses Bakery API v1 — the current stable API for Checkmk 2.4.
"""

import logging
from pathlib import Path
from typing import Any

from .bakery_api.v1 import OS, FileGenerator, Plugin, PluginConfig, register

logger = logging.getLogger(__name__)


def _resolve_password(pw_value: Any) -> str:
    """Resolve a Password form-spec value to cleartext for agent config deployment.

    The CheckMK ``Password`` form spec produces tuples:

    * Explicit password:
      ``("cmk_postprocessed", "explicit_password", ("<id>", "<cleartext>"))``
    * Password store reference:
      ``("cmk_postprocessed", "stored_password", ("<store_id>", ""))``

    A plain ``str`` is accepted as a legacy/fallback value.
    """
    if isinstance(pw_value, str):
        return pw_value

    if isinstance(pw_value, tuple) and len(pw_value) == 3:
        _marker, pw_type, pw_data = pw_value
        if isinstance(pw_data, tuple) and len(pw_data) >= 2:
            if pw_type == "explicit_password":
                return str(pw_data[1])
            if pw_type == "stored_password":
                try:
                    # Imported lazily so a missing module can be handled below
                    from cmk.utils.password_store import lookup_for_bakery  # noqa: PLC0415

                    return str(lookup_for_bakery(pw_data[0]))
                except ImportError:
                    logger.exception(
                        "Cannot resolve stored password '%s': cmk.utils.password_store not available",
                        pw_data[0],
                    )
                    return ""
                except ValueError:
                    logger.exception(
                        "Stored password '%s' not found in password store",
                        pw_data[0],
                    )
                    return ""

    logger.warning("Unexpected password value format: %s", type(pw_value).__name__)
    return str(pw_value)


def _build_config_lines(conf: dict) -> list[str]:
    """Generate INI-style keystore.cfg content from WATO configuration."""
    lines = [
        "# Java Keystore Certificate Monitor Configuration",
        "# Generated by CheckMK Agent Bakery - do not edit manually",
        "",
    ]

    keystores = conf.get("keystores", [])
    # An empty field means "use the default", as promised by the ruleset help texts
    keytool_default = conf.get("keytool", "").strip() or "/usr/bin/keytool"

    for ks in keystores:
        ks_path = ks.get("path", "")
        if not ks_path:
            continue

        lines.append(f"[{ks_path}]")
        lines.append(f"password={_resolve_password(ks.get('password', ''))}")

        # Aliases: "all", or "specific" with a list of alias names
        aliases_config = ks.get("aliases", ("all", None))
        if isinstance(aliases_config, tuple):
            choice = aliases_config[0]
            value = aliases_config[1] if len(aliases_config) > 1 else None
            if choice == "specific" and value:
                lines.append(f"aliases={','.join(value)}")
            else:
                lines.append("aliases=ALL")
        else:
            lines.append("aliases=ALL")

        lines.append(f"keytool={ks.get('keytool', '').strip() or keytool_default}")

        storetype = ks.get("storetype", ("auto", None))
        if isinstance(storetype, tuple):
            choice = storetype[0]
            if choice != "auto":
                lines.append(f"storetype={choice.upper()}")
        elif storetype and storetype != "auto":
            lines.append(f"storetype={storetype}")

        lines.append("")

    return lines


def get_keystore_files(conf: Any) -> FileGenerator:
    """Yield the agent plugin and config files for deployment via the Agent Bakery."""
    if conf is None:
        return

    deploy = conf.get("deploy")
    if deploy is None:
        return

    # Rulesets API yields ("nodeploy", None); plain "nodeploy" is the legacy form
    deploy_choice = deploy[0] if isinstance(deploy, tuple) else deploy
    if deploy_choice == "nodeploy":
        return

    # Generate configuration file
    config_lines = _build_config_lines(conf)
    yield PluginConfig(
        base_os=OS.LINUX,
        lines=config_lines,
        target=Path("keystore.cfg"),
        include_header=False,
    )

    # Deploy plugin binary
    if isinstance(deploy, tuple):
        choice, value = deploy
        if choice == "interval" and value is not None:
            yield Plugin(
                base_os=OS.LINUX,
                source=Path("keystore"),
                interval=int(value),
            )
            return

    # Fallback: deploy without caching interval
    yield Plugin(
        base_os=OS.LINUX,
        source=Path("keystore"),
    )


register.bakery_plugin(
    name="keystore",
    files_function=get_keystore_files,
)
